// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.lightstreamer.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"P\n\007TestObj\022\021\n\ttimestamp\030" +
      "\001 \001(\t\022\020\n\010fstValue\030\002 \001(\t\022\020\n\010sndValue\030\003 \001(" +
      "\t\022\016\n\006intNum\030\004 \001(\005B\033\n\027com.lightstreamer.p" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TestObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestObj_descriptor,
        new java.lang.String[] { "Timestamp", "FstValue", "SndValue", "IntNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
