// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price-info.proto

package com.lightstreamer.proto;

/**
 * Protobuf type {@code PriceInfo}
 */
public  final class PriceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PriceInfo)
    PriceInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceInfo.newBuilder() to construct.
  private PriceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceInfo() {
    command_ = "";
    symbol_ = "";
    currTime_ = "";
    lSTime_ = "";
    lSTick_ = "";
    lSMMID_ = "";
    bidTick_ = "";
    bidMMID_ = "";
    bidTime_ = "";
    askMMID_ = "";
    askTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PriceInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PriceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            command_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 29: {

            lS_ = input.readFloat();
            break;
          }
          case 32: {

            lSSize_ = input.readUInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            lSTime_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            lSTick_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            lSMMID_ = s;
            break;
          }
          case 69: {

            bid_ = input.readFloat();
            break;
          }
          case 72: {

            bidSize_ = input.readUInt64();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            bidTick_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            bidMMID_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            bidTime_ = s;
            break;
          }
          case 109: {

            ask_ = input.readFloat();
            break;
          }
          case 112: {

            askSize_ = input.readUInt64();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            askMMID_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            askTime_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            currTime_ = s;
            break;
          }
          case 149: {

            high_ = input.readFloat();
            break;
          }
          case 157: {

            low_ = input.readFloat();
            break;
          }
          case 160: {

            vol_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lightstreamer.proto.PriceInfoOuterClass.internal_static_PriceInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lightstreamer.proto.PriceInfoOuterClass.internal_static_PriceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lightstreamer.proto.PriceInfo.class, com.lightstreamer.proto.PriceInfo.Builder.class);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object command_;
  /**
   * <code>string Command = 1;</code>
   * @return The command.
   */
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>string Command = 1;</code>
   * @return The bytes for command.
   */
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 2;
  private volatile java.lang.Object symbol_;
  /**
   * <code>string Symbol = 2;</code>
   * @return The symbol.
   */
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string Symbol = 2;</code>
   * @return The bytes for symbol.
   */
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRTIME_FIELD_NUMBER = 17;
  private volatile java.lang.Object currTime_;
  /**
   * <code>string CurrTime = 17;</code>
   * @return The currTime.
   */
  public java.lang.String getCurrTime() {
    java.lang.Object ref = currTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currTime_ = s;
      return s;
    }
  }
  /**
   * <code>string CurrTime = 17;</code>
   * @return The bytes for currTime.
   */
  public com.google.protobuf.ByteString
      getCurrTimeBytes() {
    java.lang.Object ref = currTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LS_FIELD_NUMBER = 3;
  private float lS_;
  /**
   * <code>float LS = 3;</code>
   * @return The lS.
   */
  public float getLS() {
    return lS_;
  }

  public static final int LSSIZE_FIELD_NUMBER = 4;
  private long lSSize_;
  /**
   * <code>uint64 LSSize = 4;</code>
   * @return The lSSize.
   */
  public long getLSSize() {
    return lSSize_;
  }

  public static final int LSTIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object lSTime_;
  /**
   * <code>string LSTime = 5;</code>
   * @return The lSTime.
   */
  public java.lang.String getLSTime() {
    java.lang.Object ref = lSTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lSTime_ = s;
      return s;
    }
  }
  /**
   * <code>string LSTime = 5;</code>
   * @return The bytes for lSTime.
   */
  public com.google.protobuf.ByteString
      getLSTimeBytes() {
    java.lang.Object ref = lSTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lSTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LSTICK_FIELD_NUMBER = 6;
  private volatile java.lang.Object lSTick_;
  /**
   * <code>string LSTick = 6;</code>
   * @return The lSTick.
   */
  public java.lang.String getLSTick() {
    java.lang.Object ref = lSTick_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lSTick_ = s;
      return s;
    }
  }
  /**
   * <code>string LSTick = 6;</code>
   * @return The bytes for lSTick.
   */
  public com.google.protobuf.ByteString
      getLSTickBytes() {
    java.lang.Object ref = lSTick_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lSTick_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LSMMID_FIELD_NUMBER = 7;
  private volatile java.lang.Object lSMMID_;
  /**
   * <code>string LSMMID = 7;</code>
   * @return The lSMMID.
   */
  public java.lang.String getLSMMID() {
    java.lang.Object ref = lSMMID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lSMMID_ = s;
      return s;
    }
  }
  /**
   * <code>string LSMMID = 7;</code>
   * @return The bytes for lSMMID.
   */
  public com.google.protobuf.ByteString
      getLSMMIDBytes() {
    java.lang.Object ref = lSMMID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lSMMID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_FIELD_NUMBER = 8;
  private float bid_;
  /**
   * <code>float Bid = 8;</code>
   * @return The bid.
   */
  public float getBid() {
    return bid_;
  }

  public static final int BIDSIZE_FIELD_NUMBER = 9;
  private long bidSize_;
  /**
   * <code>uint64 BidSize = 9;</code>
   * @return The bidSize.
   */
  public long getBidSize() {
    return bidSize_;
  }

  public static final int BIDTICK_FIELD_NUMBER = 10;
  private volatile java.lang.Object bidTick_;
  /**
   * <code>string BidTick = 10;</code>
   * @return The bidTick.
   */
  public java.lang.String getBidTick() {
    java.lang.Object ref = bidTick_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bidTick_ = s;
      return s;
    }
  }
  /**
   * <code>string BidTick = 10;</code>
   * @return The bytes for bidTick.
   */
  public com.google.protobuf.ByteString
      getBidTickBytes() {
    java.lang.Object ref = bidTick_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bidTick_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIDMMID_FIELD_NUMBER = 11;
  private volatile java.lang.Object bidMMID_;
  /**
   * <code>string BidMMID = 11;</code>
   * @return The bidMMID.
   */
  public java.lang.String getBidMMID() {
    java.lang.Object ref = bidMMID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bidMMID_ = s;
      return s;
    }
  }
  /**
   * <code>string BidMMID = 11;</code>
   * @return The bytes for bidMMID.
   */
  public com.google.protobuf.ByteString
      getBidMMIDBytes() {
    java.lang.Object ref = bidMMID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bidMMID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIDTIME_FIELD_NUMBER = 12;
  private volatile java.lang.Object bidTime_;
  /**
   * <code>string BidTime = 12;</code>
   * @return The bidTime.
   */
  public java.lang.String getBidTime() {
    java.lang.Object ref = bidTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bidTime_ = s;
      return s;
    }
  }
  /**
   * <code>string BidTime = 12;</code>
   * @return The bytes for bidTime.
   */
  public com.google.protobuf.ByteString
      getBidTimeBytes() {
    java.lang.Object ref = bidTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bidTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASK_FIELD_NUMBER = 13;
  private float ask_;
  /**
   * <code>float Ask = 13;</code>
   * @return The ask.
   */
  public float getAsk() {
    return ask_;
  }

  public static final int ASKSIZE_FIELD_NUMBER = 14;
  private long askSize_;
  /**
   * <code>uint64 AskSize = 14;</code>
   * @return The askSize.
   */
  public long getAskSize() {
    return askSize_;
  }

  public static final int ASKMMID_FIELD_NUMBER = 15;
  private volatile java.lang.Object askMMID_;
  /**
   * <code>string AskMMID = 15;</code>
   * @return The askMMID.
   */
  public java.lang.String getAskMMID() {
    java.lang.Object ref = askMMID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      askMMID_ = s;
      return s;
    }
  }
  /**
   * <code>string AskMMID = 15;</code>
   * @return The bytes for askMMID.
   */
  public com.google.protobuf.ByteString
      getAskMMIDBytes() {
    java.lang.Object ref = askMMID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      askMMID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASKTIME_FIELD_NUMBER = 16;
  private volatile java.lang.Object askTime_;
  /**
   * <code>string AskTime = 16;</code>
   * @return The askTime.
   */
  public java.lang.String getAskTime() {
    java.lang.Object ref = askTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      askTime_ = s;
      return s;
    }
  }
  /**
   * <code>string AskTime = 16;</code>
   * @return The bytes for askTime.
   */
  public com.google.protobuf.ByteString
      getAskTimeBytes() {
    java.lang.Object ref = askTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      askTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGH_FIELD_NUMBER = 18;
  private float high_;
  /**
   * <code>float High = 18;</code>
   * @return The high.
   */
  public float getHigh() {
    return high_;
  }

  public static final int LOW_FIELD_NUMBER = 19;
  private float low_;
  /**
   * <code>float Low = 19;</code>
   * @return The low.
   */
  public float getLow() {
    return low_;
  }

  public static final int VOL_FIELD_NUMBER = 20;
  private long vol_;
  /**
   * <code>uint64 Vol = 20;</code>
   * @return The vol.
   */
  public long getVol() {
    return vol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCommandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, command_);
    }
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
    }
    if (lS_ != 0F) {
      output.writeFloat(3, lS_);
    }
    if (lSSize_ != 0L) {
      output.writeUInt64(4, lSSize_);
    }
    if (!getLSTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lSTime_);
    }
    if (!getLSTickBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lSTick_);
    }
    if (!getLSMMIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lSMMID_);
    }
    if (bid_ != 0F) {
      output.writeFloat(8, bid_);
    }
    if (bidSize_ != 0L) {
      output.writeUInt64(9, bidSize_);
    }
    if (!getBidTickBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, bidTick_);
    }
    if (!getBidMMIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, bidMMID_);
    }
    if (!getBidTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, bidTime_);
    }
    if (ask_ != 0F) {
      output.writeFloat(13, ask_);
    }
    if (askSize_ != 0L) {
      output.writeUInt64(14, askSize_);
    }
    if (!getAskMMIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, askMMID_);
    }
    if (!getAskTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, askTime_);
    }
    if (!getCurrTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, currTime_);
    }
    if (high_ != 0F) {
      output.writeFloat(18, high_);
    }
    if (low_ != 0F) {
      output.writeFloat(19, low_);
    }
    if (vol_ != 0L) {
      output.writeUInt64(20, vol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCommandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, command_);
    }
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
    }
    if (lS_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, lS_);
    }
    if (lSSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, lSSize_);
    }
    if (!getLSTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lSTime_);
    }
    if (!getLSTickBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lSTick_);
    }
    if (!getLSMMIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lSMMID_);
    }
    if (bid_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, bid_);
    }
    if (bidSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, bidSize_);
    }
    if (!getBidTickBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, bidTick_);
    }
    if (!getBidMMIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, bidMMID_);
    }
    if (!getBidTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, bidTime_);
    }
    if (ask_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, ask_);
    }
    if (askSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, askSize_);
    }
    if (!getAskMMIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, askMMID_);
    }
    if (!getAskTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, askTime_);
    }
    if (!getCurrTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, currTime_);
    }
    if (high_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(18, high_);
    }
    if (low_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(19, low_);
    }
    if (vol_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(20, vol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lightstreamer.proto.PriceInfo)) {
      return super.equals(obj);
    }
    com.lightstreamer.proto.PriceInfo other = (com.lightstreamer.proto.PriceInfo) obj;

    if (!getCommand()
        .equals(other.getCommand())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getCurrTime()
        .equals(other.getCurrTime())) return false;
    if (java.lang.Float.floatToIntBits(getLS())
        != java.lang.Float.floatToIntBits(
            other.getLS())) return false;
    if (getLSSize()
        != other.getLSSize()) return false;
    if (!getLSTime()
        .equals(other.getLSTime())) return false;
    if (!getLSTick()
        .equals(other.getLSTick())) return false;
    if (!getLSMMID()
        .equals(other.getLSMMID())) return false;
    if (java.lang.Float.floatToIntBits(getBid())
        != java.lang.Float.floatToIntBits(
            other.getBid())) return false;
    if (getBidSize()
        != other.getBidSize()) return false;
    if (!getBidTick()
        .equals(other.getBidTick())) return false;
    if (!getBidMMID()
        .equals(other.getBidMMID())) return false;
    if (!getBidTime()
        .equals(other.getBidTime())) return false;
    if (java.lang.Float.floatToIntBits(getAsk())
        != java.lang.Float.floatToIntBits(
            other.getAsk())) return false;
    if (getAskSize()
        != other.getAskSize()) return false;
    if (!getAskMMID()
        .equals(other.getAskMMID())) return false;
    if (!getAskTime()
        .equals(other.getAskTime())) return false;
    if (java.lang.Float.floatToIntBits(getHigh())
        != java.lang.Float.floatToIntBits(
            other.getHigh())) return false;
    if (java.lang.Float.floatToIntBits(getLow())
        != java.lang.Float.floatToIntBits(
            other.getLow())) return false;
    if (getVol()
        != other.getVol()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + getCommand().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + CURRTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCurrTime().hashCode();
    hash = (37 * hash) + LS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLS());
    hash = (37 * hash) + LSSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLSSize());
    hash = (37 * hash) + LSTIME_FIELD_NUMBER;
    hash = (53 * hash) + getLSTime().hashCode();
    hash = (37 * hash) + LSTICK_FIELD_NUMBER;
    hash = (53 * hash) + getLSTick().hashCode();
    hash = (37 * hash) + LSMMID_FIELD_NUMBER;
    hash = (53 * hash) + getLSMMID().hashCode();
    hash = (37 * hash) + BID_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBid());
    hash = (37 * hash) + BIDSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBidSize());
    hash = (37 * hash) + BIDTICK_FIELD_NUMBER;
    hash = (53 * hash) + getBidTick().hashCode();
    hash = (37 * hash) + BIDMMID_FIELD_NUMBER;
    hash = (53 * hash) + getBidMMID().hashCode();
    hash = (37 * hash) + BIDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getBidTime().hashCode();
    hash = (37 * hash) + ASK_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAsk());
    hash = (37 * hash) + ASKSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAskSize());
    hash = (37 * hash) + ASKMMID_FIELD_NUMBER;
    hash = (53 * hash) + getAskMMID().hashCode();
    hash = (37 * hash) + ASKTIME_FIELD_NUMBER;
    hash = (53 * hash) + getAskTime().hashCode();
    hash = (37 * hash) + HIGH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHigh());
    hash = (37 * hash) + LOW_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLow());
    hash = (37 * hash) + VOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVol());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lightstreamer.proto.PriceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstreamer.proto.PriceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.PriceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.PriceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lightstreamer.proto.PriceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PriceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PriceInfo)
      com.lightstreamer.proto.PriceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstreamer.proto.PriceInfoOuterClass.internal_static_PriceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstreamer.proto.PriceInfoOuterClass.internal_static_PriceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstreamer.proto.PriceInfo.class, com.lightstreamer.proto.PriceInfo.Builder.class);
    }

    // Construct using com.lightstreamer.proto.PriceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      command_ = "";

      symbol_ = "";

      currTime_ = "";

      lS_ = 0F;

      lSSize_ = 0L;

      lSTime_ = "";

      lSTick_ = "";

      lSMMID_ = "";

      bid_ = 0F;

      bidSize_ = 0L;

      bidTick_ = "";

      bidMMID_ = "";

      bidTime_ = "";

      ask_ = 0F;

      askSize_ = 0L;

      askMMID_ = "";

      askTime_ = "";

      high_ = 0F;

      low_ = 0F;

      vol_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lightstreamer.proto.PriceInfoOuterClass.internal_static_PriceInfo_descriptor;
    }

    @java.lang.Override
    public com.lightstreamer.proto.PriceInfo getDefaultInstanceForType() {
      return com.lightstreamer.proto.PriceInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.lightstreamer.proto.PriceInfo build() {
      com.lightstreamer.proto.PriceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lightstreamer.proto.PriceInfo buildPartial() {
      com.lightstreamer.proto.PriceInfo result = new com.lightstreamer.proto.PriceInfo(this);
      result.command_ = command_;
      result.symbol_ = symbol_;
      result.currTime_ = currTime_;
      result.lS_ = lS_;
      result.lSSize_ = lSSize_;
      result.lSTime_ = lSTime_;
      result.lSTick_ = lSTick_;
      result.lSMMID_ = lSMMID_;
      result.bid_ = bid_;
      result.bidSize_ = bidSize_;
      result.bidTick_ = bidTick_;
      result.bidMMID_ = bidMMID_;
      result.bidTime_ = bidTime_;
      result.ask_ = ask_;
      result.askSize_ = askSize_;
      result.askMMID_ = askMMID_;
      result.askTime_ = askTime_;
      result.high_ = high_;
      result.low_ = low_;
      result.vol_ = vol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lightstreamer.proto.PriceInfo) {
        return mergeFrom((com.lightstreamer.proto.PriceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lightstreamer.proto.PriceInfo other) {
      if (other == com.lightstreamer.proto.PriceInfo.getDefaultInstance()) return this;
      if (!other.getCommand().isEmpty()) {
        command_ = other.command_;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (!other.getCurrTime().isEmpty()) {
        currTime_ = other.currTime_;
        onChanged();
      }
      if (other.getLS() != 0F) {
        setLS(other.getLS());
      }
      if (other.getLSSize() != 0L) {
        setLSSize(other.getLSSize());
      }
      if (!other.getLSTime().isEmpty()) {
        lSTime_ = other.lSTime_;
        onChanged();
      }
      if (!other.getLSTick().isEmpty()) {
        lSTick_ = other.lSTick_;
        onChanged();
      }
      if (!other.getLSMMID().isEmpty()) {
        lSMMID_ = other.lSMMID_;
        onChanged();
      }
      if (other.getBid() != 0F) {
        setBid(other.getBid());
      }
      if (other.getBidSize() != 0L) {
        setBidSize(other.getBidSize());
      }
      if (!other.getBidTick().isEmpty()) {
        bidTick_ = other.bidTick_;
        onChanged();
      }
      if (!other.getBidMMID().isEmpty()) {
        bidMMID_ = other.bidMMID_;
        onChanged();
      }
      if (!other.getBidTime().isEmpty()) {
        bidTime_ = other.bidTime_;
        onChanged();
      }
      if (other.getAsk() != 0F) {
        setAsk(other.getAsk());
      }
      if (other.getAskSize() != 0L) {
        setAskSize(other.getAskSize());
      }
      if (!other.getAskMMID().isEmpty()) {
        askMMID_ = other.askMMID_;
        onChanged();
      }
      if (!other.getAskTime().isEmpty()) {
        askTime_ = other.askTime_;
        onChanged();
      }
      if (other.getHigh() != 0F) {
        setHigh(other.getHigh());
      }
      if (other.getLow() != 0F) {
        setLow(other.getLow());
      }
      if (other.getVol() != 0L) {
        setVol(other.getVol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lightstreamer.proto.PriceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lightstreamer.proto.PriceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object command_ = "";
    /**
     * <code>string Command = 1;</code>
     * @return The command.
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Command = 1;</code>
     * @return The bytes for command.
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = getDefaultInstance().getCommand();
      onChanged();
      return this;
    }
    /**
     * <code>string Command = 1;</code>
     * @param value The bytes for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      command_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string Symbol = 2;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Symbol = 2;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Symbol = 2;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Symbol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string Symbol = 2;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currTime_ = "";
    /**
     * <code>string CurrTime = 17;</code>
     * @return The currTime.
     */
    public java.lang.String getCurrTime() {
      java.lang.Object ref = currTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string CurrTime = 17;</code>
     * @return The bytes for currTime.
     */
    public com.google.protobuf.ByteString
        getCurrTimeBytes() {
      java.lang.Object ref = currTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string CurrTime = 17;</code>
     * @param value The currTime to set.
     * @return This builder for chaining.
     */
    public Builder setCurrTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string CurrTime = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrTime() {
      
      currTime_ = getDefaultInstance().getCurrTime();
      onChanged();
      return this;
    }
    /**
     * <code>string CurrTime = 17;</code>
     * @param value The bytes for currTime to set.
     * @return This builder for chaining.
     */
    public Builder setCurrTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currTime_ = value;
      onChanged();
      return this;
    }

    private float lS_ ;
    /**
     * <code>float LS = 3;</code>
     * @return The lS.
     */
    public float getLS() {
      return lS_;
    }
    /**
     * <code>float LS = 3;</code>
     * @param value The lS to set.
     * @return This builder for chaining.
     */
    public Builder setLS(float value) {
      
      lS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float LS = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLS() {
      
      lS_ = 0F;
      onChanged();
      return this;
    }

    private long lSSize_ ;
    /**
     * <code>uint64 LSSize = 4;</code>
     * @return The lSSize.
     */
    public long getLSSize() {
      return lSSize_;
    }
    /**
     * <code>uint64 LSSize = 4;</code>
     * @param value The lSSize to set.
     * @return This builder for chaining.
     */
    public Builder setLSSize(long value) {
      
      lSSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 LSSize = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLSSize() {
      
      lSSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object lSTime_ = "";
    /**
     * <code>string LSTime = 5;</code>
     * @return The lSTime.
     */
    public java.lang.String getLSTime() {
      java.lang.Object ref = lSTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lSTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string LSTime = 5;</code>
     * @return The bytes for lSTime.
     */
    public com.google.protobuf.ByteString
        getLSTimeBytes() {
      java.lang.Object ref = lSTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lSTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string LSTime = 5;</code>
     * @param value The lSTime to set.
     * @return This builder for chaining.
     */
    public Builder setLSTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lSTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string LSTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLSTime() {
      
      lSTime_ = getDefaultInstance().getLSTime();
      onChanged();
      return this;
    }
    /**
     * <code>string LSTime = 5;</code>
     * @param value The bytes for lSTime to set.
     * @return This builder for chaining.
     */
    public Builder setLSTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lSTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lSTick_ = "";
    /**
     * <code>string LSTick = 6;</code>
     * @return The lSTick.
     */
    public java.lang.String getLSTick() {
      java.lang.Object ref = lSTick_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lSTick_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string LSTick = 6;</code>
     * @return The bytes for lSTick.
     */
    public com.google.protobuf.ByteString
        getLSTickBytes() {
      java.lang.Object ref = lSTick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lSTick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string LSTick = 6;</code>
     * @param value The lSTick to set.
     * @return This builder for chaining.
     */
    public Builder setLSTick(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lSTick_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string LSTick = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLSTick() {
      
      lSTick_ = getDefaultInstance().getLSTick();
      onChanged();
      return this;
    }
    /**
     * <code>string LSTick = 6;</code>
     * @param value The bytes for lSTick to set.
     * @return This builder for chaining.
     */
    public Builder setLSTickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lSTick_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lSMMID_ = "";
    /**
     * <code>string LSMMID = 7;</code>
     * @return The lSMMID.
     */
    public java.lang.String getLSMMID() {
      java.lang.Object ref = lSMMID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lSMMID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string LSMMID = 7;</code>
     * @return The bytes for lSMMID.
     */
    public com.google.protobuf.ByteString
        getLSMMIDBytes() {
      java.lang.Object ref = lSMMID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lSMMID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string LSMMID = 7;</code>
     * @param value The lSMMID to set.
     * @return This builder for chaining.
     */
    public Builder setLSMMID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lSMMID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string LSMMID = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLSMMID() {
      
      lSMMID_ = getDefaultInstance().getLSMMID();
      onChanged();
      return this;
    }
    /**
     * <code>string LSMMID = 7;</code>
     * @param value The bytes for lSMMID to set.
     * @return This builder for chaining.
     */
    public Builder setLSMMIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lSMMID_ = value;
      onChanged();
      return this;
    }

    private float bid_ ;
    /**
     * <code>float Bid = 8;</code>
     * @return The bid.
     */
    public float getBid() {
      return bid_;
    }
    /**
     * <code>float Bid = 8;</code>
     * @param value The bid to set.
     * @return This builder for chaining.
     */
    public Builder setBid(float value) {
      
      bid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float Bid = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBid() {
      
      bid_ = 0F;
      onChanged();
      return this;
    }

    private long bidSize_ ;
    /**
     * <code>uint64 BidSize = 9;</code>
     * @return The bidSize.
     */
    public long getBidSize() {
      return bidSize_;
    }
    /**
     * <code>uint64 BidSize = 9;</code>
     * @param value The bidSize to set.
     * @return This builder for chaining.
     */
    public Builder setBidSize(long value) {
      
      bidSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 BidSize = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidSize() {
      
      bidSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bidTick_ = "";
    /**
     * <code>string BidTick = 10;</code>
     * @return The bidTick.
     */
    public java.lang.String getBidTick() {
      java.lang.Object ref = bidTick_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidTick_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string BidTick = 10;</code>
     * @return The bytes for bidTick.
     */
    public com.google.protobuf.ByteString
        getBidTickBytes() {
      java.lang.Object ref = bidTick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidTick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string BidTick = 10;</code>
     * @param value The bidTick to set.
     * @return This builder for chaining.
     */
    public Builder setBidTick(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bidTick_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string BidTick = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidTick() {
      
      bidTick_ = getDefaultInstance().getBidTick();
      onChanged();
      return this;
    }
    /**
     * <code>string BidTick = 10;</code>
     * @param value The bytes for bidTick to set.
     * @return This builder for chaining.
     */
    public Builder setBidTickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bidTick_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bidMMID_ = "";
    /**
     * <code>string BidMMID = 11;</code>
     * @return The bidMMID.
     */
    public java.lang.String getBidMMID() {
      java.lang.Object ref = bidMMID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidMMID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string BidMMID = 11;</code>
     * @return The bytes for bidMMID.
     */
    public com.google.protobuf.ByteString
        getBidMMIDBytes() {
      java.lang.Object ref = bidMMID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidMMID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string BidMMID = 11;</code>
     * @param value The bidMMID to set.
     * @return This builder for chaining.
     */
    public Builder setBidMMID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bidMMID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string BidMMID = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidMMID() {
      
      bidMMID_ = getDefaultInstance().getBidMMID();
      onChanged();
      return this;
    }
    /**
     * <code>string BidMMID = 11;</code>
     * @param value The bytes for bidMMID to set.
     * @return This builder for chaining.
     */
    public Builder setBidMMIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bidMMID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bidTime_ = "";
    /**
     * <code>string BidTime = 12;</code>
     * @return The bidTime.
     */
    public java.lang.String getBidTime() {
      java.lang.Object ref = bidTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string BidTime = 12;</code>
     * @return The bytes for bidTime.
     */
    public com.google.protobuf.ByteString
        getBidTimeBytes() {
      java.lang.Object ref = bidTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string BidTime = 12;</code>
     * @param value The bidTime to set.
     * @return This builder for chaining.
     */
    public Builder setBidTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bidTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string BidTime = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidTime() {
      
      bidTime_ = getDefaultInstance().getBidTime();
      onChanged();
      return this;
    }
    /**
     * <code>string BidTime = 12;</code>
     * @param value The bytes for bidTime to set.
     * @return This builder for chaining.
     */
    public Builder setBidTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bidTime_ = value;
      onChanged();
      return this;
    }

    private float ask_ ;
    /**
     * <code>float Ask = 13;</code>
     * @return The ask.
     */
    public float getAsk() {
      return ask_;
    }
    /**
     * <code>float Ask = 13;</code>
     * @param value The ask to set.
     * @return This builder for chaining.
     */
    public Builder setAsk(float value) {
      
      ask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float Ask = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsk() {
      
      ask_ = 0F;
      onChanged();
      return this;
    }

    private long askSize_ ;
    /**
     * <code>uint64 AskSize = 14;</code>
     * @return The askSize.
     */
    public long getAskSize() {
      return askSize_;
    }
    /**
     * <code>uint64 AskSize = 14;</code>
     * @param value The askSize to set.
     * @return This builder for chaining.
     */
    public Builder setAskSize(long value) {
      
      askSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 AskSize = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskSize() {
      
      askSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object askMMID_ = "";
    /**
     * <code>string AskMMID = 15;</code>
     * @return The askMMID.
     */
    public java.lang.String getAskMMID() {
      java.lang.Object ref = askMMID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        askMMID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string AskMMID = 15;</code>
     * @return The bytes for askMMID.
     */
    public com.google.protobuf.ByteString
        getAskMMIDBytes() {
      java.lang.Object ref = askMMID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        askMMID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AskMMID = 15;</code>
     * @param value The askMMID to set.
     * @return This builder for chaining.
     */
    public Builder setAskMMID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      askMMID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AskMMID = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskMMID() {
      
      askMMID_ = getDefaultInstance().getAskMMID();
      onChanged();
      return this;
    }
    /**
     * <code>string AskMMID = 15;</code>
     * @param value The bytes for askMMID to set.
     * @return This builder for chaining.
     */
    public Builder setAskMMIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      askMMID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object askTime_ = "";
    /**
     * <code>string AskTime = 16;</code>
     * @return The askTime.
     */
    public java.lang.String getAskTime() {
      java.lang.Object ref = askTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        askTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string AskTime = 16;</code>
     * @return The bytes for askTime.
     */
    public com.google.protobuf.ByteString
        getAskTimeBytes() {
      java.lang.Object ref = askTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        askTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AskTime = 16;</code>
     * @param value The askTime to set.
     * @return This builder for chaining.
     */
    public Builder setAskTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      askTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AskTime = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskTime() {
      
      askTime_ = getDefaultInstance().getAskTime();
      onChanged();
      return this;
    }
    /**
     * <code>string AskTime = 16;</code>
     * @param value The bytes for askTime to set.
     * @return This builder for chaining.
     */
    public Builder setAskTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      askTime_ = value;
      onChanged();
      return this;
    }

    private float high_ ;
    /**
     * <code>float High = 18;</code>
     * @return The high.
     */
    public float getHigh() {
      return high_;
    }
    /**
     * <code>float High = 18;</code>
     * @param value The high to set.
     * @return This builder for chaining.
     */
    public Builder setHigh(float value) {
      
      high_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float High = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearHigh() {
      
      high_ = 0F;
      onChanged();
      return this;
    }

    private float low_ ;
    /**
     * <code>float Low = 19;</code>
     * @return The low.
     */
    public float getLow() {
      return low_;
    }
    /**
     * <code>float Low = 19;</code>
     * @param value The low to set.
     * @return This builder for chaining.
     */
    public Builder setLow(float value) {
      
      low_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float Low = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearLow() {
      
      low_ = 0F;
      onChanged();
      return this;
    }

    private long vol_ ;
    /**
     * <code>uint64 Vol = 20;</code>
     * @return The vol.
     */
    public long getVol() {
      return vol_;
    }
    /**
     * <code>uint64 Vol = 20;</code>
     * @param value The vol to set.
     * @return This builder for chaining.
     */
    public Builder setVol(long value) {
      
      vol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 Vol = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearVol() {
      
      vol_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PriceInfo)
  }

  // @@protoc_insertion_point(class_scope:PriceInfo)
  private static final com.lightstreamer.proto.PriceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lightstreamer.proto.PriceInfo();
  }

  public static com.lightstreamer.proto.PriceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceInfo>
      PARSER = new com.google.protobuf.AbstractParser<PriceInfo>() {
    @java.lang.Override
    public PriceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PriceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PriceInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lightstreamer.proto.PriceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

