// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price-info.proto

package com.lightstreamer.proto;

public interface PriceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PriceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string Command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>string Symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string Symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string CurrTime = 17;</code>
   * @return The currTime.
   */
  java.lang.String getCurrTime();
  /**
   * <code>string CurrTime = 17;</code>
   * @return The bytes for currTime.
   */
  com.google.protobuf.ByteString
      getCurrTimeBytes();

  /**
   * <code>float LS = 3;</code>
   * @return The lS.
   */
  float getLS();

  /**
   * <code>uint64 LSSize = 4;</code>
   * @return The lSSize.
   */
  long getLSSize();

  /**
   * <code>string LSTime = 5;</code>
   * @return The lSTime.
   */
  java.lang.String getLSTime();
  /**
   * <code>string LSTime = 5;</code>
   * @return The bytes for lSTime.
   */
  com.google.protobuf.ByteString
      getLSTimeBytes();

  /**
   * <code>string LSTick = 6;</code>
   * @return The lSTick.
   */
  java.lang.String getLSTick();
  /**
   * <code>string LSTick = 6;</code>
   * @return The bytes for lSTick.
   */
  com.google.protobuf.ByteString
      getLSTickBytes();

  /**
   * <code>string LSMMID = 7;</code>
   * @return The lSMMID.
   */
  java.lang.String getLSMMID();
  /**
   * <code>string LSMMID = 7;</code>
   * @return The bytes for lSMMID.
   */
  com.google.protobuf.ByteString
      getLSMMIDBytes();

  /**
   * <code>float Bid = 8;</code>
   * @return The bid.
   */
  float getBid();

  /**
   * <code>uint64 BidSize = 9;</code>
   * @return The bidSize.
   */
  long getBidSize();

  /**
   * <code>string BidTick = 10;</code>
   * @return The bidTick.
   */
  java.lang.String getBidTick();
  /**
   * <code>string BidTick = 10;</code>
   * @return The bytes for bidTick.
   */
  com.google.protobuf.ByteString
      getBidTickBytes();

  /**
   * <code>string BidMMID = 11;</code>
   * @return The bidMMID.
   */
  java.lang.String getBidMMID();
  /**
   * <code>string BidMMID = 11;</code>
   * @return The bytes for bidMMID.
   */
  com.google.protobuf.ByteString
      getBidMMIDBytes();

  /**
   * <code>string BidTime = 12;</code>
   * @return The bidTime.
   */
  java.lang.String getBidTime();
  /**
   * <code>string BidTime = 12;</code>
   * @return The bytes for bidTime.
   */
  com.google.protobuf.ByteString
      getBidTimeBytes();

  /**
   * <code>float Ask = 13;</code>
   * @return The ask.
   */
  float getAsk();

  /**
   * <code>uint64 AskSize = 14;</code>
   * @return The askSize.
   */
  long getAskSize();

  /**
   * <code>string AskMMID = 15;</code>
   * @return The askMMID.
   */
  java.lang.String getAskMMID();
  /**
   * <code>string AskMMID = 15;</code>
   * @return The bytes for askMMID.
   */
  com.google.protobuf.ByteString
      getAskMMIDBytes();

  /**
   * <code>string AskTime = 16;</code>
   * @return The askTime.
   */
  java.lang.String getAskTime();
  /**
   * <code>string AskTime = 16;</code>
   * @return The bytes for askTime.
   */
  com.google.protobuf.ByteString
      getAskTimeBytes();

  /**
   * <code>float High = 18;</code>
   * @return The high.
   */
  float getHigh();

  /**
   * <code>float Low = 19;</code>
   * @return The low.
   */
  float getLow();

  /**
   * <code>uint64 Vol = 20;</code>
   * @return The vol.
   */
  long getVol();
}
