// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price-info.proto

package com.lightstreamer.proto;

public final class PriceInfoOuterClass {
  private PriceInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PriceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PriceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020price-info.proto\"\303\002\n\tPriceInfo\022\017\n\007Comm" +
      "and\030\001 \001(\t\022\016\n\006Symbol\030\002 \001(\t\022\020\n\010CurrTime\030\021 " +
      "\001(\t\022\n\n\002LS\030\003 \001(\002\022\016\n\006LSSize\030\004 \001(\004\022\016\n\006LSTim" +
      "e\030\005 \001(\t\022\016\n\006LSTick\030\006 \001(\t\022\016\n\006LSMMID\030\007 \001(\t\022" +
      "\013\n\003Bid\030\010 \001(\002\022\017\n\007BidSize\030\t \001(\004\022\017\n\007BidTick" +
      "\030\n \001(\t\022\017\n\007BidMMID\030\013 \001(\t\022\017\n\007BidTime\030\014 \001(\t" +
      "\022\013\n\003Ask\030\r \001(\002\022\017\n\007AskSize\030\016 \001(\004\022\017\n\007AskMMI" +
      "D\030\017 \001(\t\022\017\n\007AskTime\030\020 \001(\t\022\014\n\004High\030\022 \001(\002\022\013" +
      "\n\003Low\030\023 \001(\002\022\013\n\003Vol\030\024 \001(\004B\033\n\027com.lightstr" +
      "eamer.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PriceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PriceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PriceInfo_descriptor,
        new java.lang.String[] { "Command", "Symbol", "CurrTime", "LS", "LSSize", "LSTime", "LSTick", "LSMMID", "Bid", "BidSize", "BidTick", "BidMMID", "BidTime", "Ask", "AskSize", "AskMMID", "AskTime", "High", "Low", "Vol", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
