// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.lightstreamer.proto;

/**
 * Protobuf type {@code TestObj}
 */
public  final class TestObj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TestObj)
    TestObjOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestObj.newBuilder() to construct.
  private TestObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestObj() {
    timestamp_ = "";
    fstValue_ = "";
    sndValue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestObj();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestObj(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            timestamp_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            fstValue_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sndValue_ = s;
            break;
          }
          case 32: {

            intNum_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lightstreamer.proto.Message.internal_static_TestObj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lightstreamer.proto.Message.internal_static_TestObj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lightstreamer.proto.TestObj.class, com.lightstreamer.proto.TestObj.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>string timestamp = 1;</code>
   * @return The timestamp.
   */
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 1;</code>
   * @return The bytes for timestamp.
   */
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FSTVALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object fstValue_;
  /**
   * <code>string fstValue = 2;</code>
   * @return The fstValue.
   */
  public java.lang.String getFstValue() {
    java.lang.Object ref = fstValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fstValue_ = s;
      return s;
    }
  }
  /**
   * <code>string fstValue = 2;</code>
   * @return The bytes for fstValue.
   */
  public com.google.protobuf.ByteString
      getFstValueBytes() {
    java.lang.Object ref = fstValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fstValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNDVALUE_FIELD_NUMBER = 3;
  private volatile java.lang.Object sndValue_;
  /**
   * <code>string sndValue = 3;</code>
   * @return The sndValue.
   */
  public java.lang.String getSndValue() {
    java.lang.Object ref = sndValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sndValue_ = s;
      return s;
    }
  }
  /**
   * <code>string sndValue = 3;</code>
   * @return The bytes for sndValue.
   */
  public com.google.protobuf.ByteString
      getSndValueBytes() {
    java.lang.Object ref = sndValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sndValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTNUM_FIELD_NUMBER = 4;
  private int intNum_;
  /**
   * <code>int32 intNum = 4;</code>
   * @return The intNum.
   */
  public int getIntNum() {
    return intNum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
    }
    if (!getFstValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fstValue_);
    }
    if (!getSndValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sndValue_);
    }
    if (intNum_ != 0) {
      output.writeInt32(4, intNum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
    }
    if (!getFstValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fstValue_);
    }
    if (!getSndValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sndValue_);
    }
    if (intNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, intNum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lightstreamer.proto.TestObj)) {
      return super.equals(obj);
    }
    com.lightstreamer.proto.TestObj other = (com.lightstreamer.proto.TestObj) obj;

    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getFstValue()
        .equals(other.getFstValue())) return false;
    if (!getSndValue()
        .equals(other.getSndValue())) return false;
    if (getIntNum()
        != other.getIntNum()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + FSTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getFstValue().hashCode();
    hash = (37 * hash) + SNDVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getSndValue().hashCode();
    hash = (37 * hash) + INTNUM_FIELD_NUMBER;
    hash = (53 * hash) + getIntNum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lightstreamer.proto.TestObj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstreamer.proto.TestObj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.TestObj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lightstreamer.proto.TestObj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lightstreamer.proto.TestObj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TestObj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TestObj)
      com.lightstreamer.proto.TestObjOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightstreamer.proto.Message.internal_static_TestObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightstreamer.proto.Message.internal_static_TestObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightstreamer.proto.TestObj.class, com.lightstreamer.proto.TestObj.Builder.class);
    }

    // Construct using com.lightstreamer.proto.TestObj.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = "";

      fstValue_ = "";

      sndValue_ = "";

      intNum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lightstreamer.proto.Message.internal_static_TestObj_descriptor;
    }

    @java.lang.Override
    public com.lightstreamer.proto.TestObj getDefaultInstanceForType() {
      return com.lightstreamer.proto.TestObj.getDefaultInstance();
    }

    @java.lang.Override
    public com.lightstreamer.proto.TestObj build() {
      com.lightstreamer.proto.TestObj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lightstreamer.proto.TestObj buildPartial() {
      com.lightstreamer.proto.TestObj result = new com.lightstreamer.proto.TestObj(this);
      result.timestamp_ = timestamp_;
      result.fstValue_ = fstValue_;
      result.sndValue_ = sndValue_;
      result.intNum_ = intNum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lightstreamer.proto.TestObj) {
        return mergeFrom((com.lightstreamer.proto.TestObj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lightstreamer.proto.TestObj other) {
      if (other == com.lightstreamer.proto.TestObj.getDefaultInstance()) return this;
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (!other.getFstValue().isEmpty()) {
        fstValue_ = other.fstValue_;
        onChanged();
      }
      if (!other.getSndValue().isEmpty()) {
        sndValue_ = other.sndValue_;
        onChanged();
      }
      if (other.getIntNum() != 0) {
        setIntNum(other.getIntNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lightstreamer.proto.TestObj parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lightstreamer.proto.TestObj) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 1;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 1;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fstValue_ = "";
    /**
     * <code>string fstValue = 2;</code>
     * @return The fstValue.
     */
    public java.lang.String getFstValue() {
      java.lang.Object ref = fstValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fstValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fstValue = 2;</code>
     * @return The bytes for fstValue.
     */
    public com.google.protobuf.ByteString
        getFstValueBytes() {
      java.lang.Object ref = fstValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fstValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fstValue = 2;</code>
     * @param value The fstValue to set.
     * @return This builder for chaining.
     */
    public Builder setFstValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fstValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fstValue = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFstValue() {
      
      fstValue_ = getDefaultInstance().getFstValue();
      onChanged();
      return this;
    }
    /**
     * <code>string fstValue = 2;</code>
     * @param value The bytes for fstValue to set.
     * @return This builder for chaining.
     */
    public Builder setFstValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fstValue_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sndValue_ = "";
    /**
     * <code>string sndValue = 3;</code>
     * @return The sndValue.
     */
    public java.lang.String getSndValue() {
      java.lang.Object ref = sndValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sndValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sndValue = 3;</code>
     * @return The bytes for sndValue.
     */
    public com.google.protobuf.ByteString
        getSndValueBytes() {
      java.lang.Object ref = sndValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sndValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sndValue = 3;</code>
     * @param value The sndValue to set.
     * @return This builder for chaining.
     */
    public Builder setSndValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sndValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sndValue = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSndValue() {
      
      sndValue_ = getDefaultInstance().getSndValue();
      onChanged();
      return this;
    }
    /**
     * <code>string sndValue = 3;</code>
     * @param value The bytes for sndValue to set.
     * @return This builder for chaining.
     */
    public Builder setSndValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sndValue_ = value;
      onChanged();
      return this;
    }

    private int intNum_ ;
    /**
     * <code>int32 intNum = 4;</code>
     * @return The intNum.
     */
    public int getIntNum() {
      return intNum_;
    }
    /**
     * <code>int32 intNum = 4;</code>
     * @param value The intNum to set.
     * @return This builder for chaining.
     */
    public Builder setIntNum(int value) {
      
      intNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intNum = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntNum() {
      
      intNum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TestObj)
  }

  // @@protoc_insertion_point(class_scope:TestObj)
  private static final com.lightstreamer.proto.TestObj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lightstreamer.proto.TestObj();
  }

  public static com.lightstreamer.proto.TestObj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestObj>
      PARSER = new com.google.protobuf.AbstractParser<TestObj>() {
    @java.lang.Override
    public TestObj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestObj(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestObj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestObj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lightstreamer.proto.TestObj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

