// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.lightstreamer.proto;

public interface TestObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string fstValue = 2;</code>
   * @return The fstValue.
   */
  java.lang.String getFstValue();
  /**
   * <code>string fstValue = 2;</code>
   * @return The bytes for fstValue.
   */
  com.google.protobuf.ByteString
      getFstValueBytes();

  /**
   * <code>string sndValue = 3;</code>
   * @return The sndValue.
   */
  java.lang.String getSndValue();
  /**
   * <code>string sndValue = 3;</code>
   * @return The bytes for sndValue.
   */
  com.google.protobuf.ByteString
      getSndValueBytes();

  /**
   * <code>int32 intNum = 4;</code>
   * @return The intNum.
   */
  int getIntNum();
}
